name: Project_Scala2-11_Spark2-4
description: ''
version: '1.0'
author: abhisheks+e2etests@prophecy.io
language: scala
buildSystem: maven
pipelines:
  pipelines/Pipeline_Scala2-11_Spark2-4:
    name: Pipeline_Scala2-11_Spark2-4
    description: Pipeline_Scala2-11_Spark2-4
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    language: scala
    createdAt: '2023-01-03 12:09:35'
    datasets:
      inputs:
      - datasets/s3_source
      outputs: []
    dependencies: {}
datasets:
  datasets/s3_source:
    name: s3_source
    description: ''
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2023-01-03 12:11:23'
    physicalDatasets:
      captain_livy:
        fabricId: 1654
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2023-01-03 12:11:23'
templates:
  templates/maven:
    name: maven
    description: null
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    language: scala
    createdAt: '2023-01-03 12:07:59'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '1359':
    projectUID: 1359
    projectName: HelloWorld
    repositoryPath: gitUri=http://gitserver:3000/zoYlsmR6_team_778/zoYlsmR6_project_1359.git&subPath=
    version: HelloWorld/1.71
    author: null
    createdAt: '2023-01-03 12:07:18'
pipelineConfigurations: {}
