WITH test_model_betaapp_1 AS (

  SELECT * 
  
  FROM {{ ref('test_model_betaapp_1')}}

),

ALL_TYPE_TABLE_SMALLER AS (

  SELECT * 
  
  FROM {{ source('QA_DATABASE.qa_simple_schema', 'ALL_TYPE_TABLE_SMALLER') }}

),

Join_1 AS (

  SELECT 
    ALL_TYPE_TABLE_SMALLER.C_NUM10 AS C_NUM10,
    ALL_TYPE_TABLE_SMALLER.C_DEC AS C_DEC,
    ALL_TYPE_TABLE_SMALLER.C_NUMERIC AS C_NUMERIC,
    ALL_TYPE_TABLE_SMALLER.C_INTEGER AS C_INTEGER,
    ALL_TYPE_TABLE_SMALLER.C_DOUBLE AS C_DOUBLE,
    ALL_TYPE_TABLE_SMALLER.C_FLOAT AS C_FLOAT,
    ALL_TYPE_TABLE_SMALLER.C_COUBLE_PRECISION AS C_COUBLE_PRECISION,
    ALL_TYPE_TABLE_SMALLER.C_REAL AS C_REAL,
    ALL_TYPE_TABLE_SMALLER.C_VARCHAR AS C_VARCHAR,
    ALL_TYPE_TABLE_SMALLER.C_VARCHAR50 AS C_VARCHAR50,
    ALL_TYPE_TABLE_SMALLER.C_CHAR AS C_CHAR,
    ALL_TYPE_TABLE_SMALLER.C_CHAR10 AS C_CHAR10,
    ALL_TYPE_TABLE_SMALLER.C_STRING AS C_STRING,
    ALL_TYPE_TABLE_SMALLER.C_STRING20 AS C_STRING20,
    ALL_TYPE_TABLE_SMALLER.C_TEXT AS C_TEXT,
    ALL_TYPE_TABLE_SMALLER.C_TEXT30 AS C_TEXT30,
    ALL_TYPE_TABLE_SMALLER.C_BINARY AS C_BINARY,
    ALL_TYPE_TABLE_SMALLER.C_BINARY100 AS C_BINARY100,
    ALL_TYPE_TABLE_SMALLER.C_VARBINARY AS C_VARBINARY,
    ALL_TYPE_TABLE_SMALLER.C_BOOL AS C_BOOL,
    ALL_TYPE_TABLE_SMALLER.C_TIMESTAMP AS C_TIMESTAMP,
    ALL_TYPE_TABLE_SMALLER.C_DATE AS C_DATE,
    ALL_TYPE_TABLE_SMALLER.C_DATETIME AS C_DATETIME,
    ALL_TYPE_TABLE_SMALLER.C_TIME AS C_TIME,
    ALL_TYPE_TABLE_SMALLER.C_ARRAY AS C_ARRAY,
    ALL_TYPE_TABLE_SMALLER.C_OBJECT AS C_OBJECT,
    ALL_TYPE_TABLE_SMALLER.C_GEOGRAPHY AS C_GEOGRAPHY,
    TEST_MODEL_BETAAPP_1.C_INT AS C_INT,
    TEST_MODEL_BETAAPP_1.C_NUM AS C_NUM
  
  FROM test_model_betaapp_1 AS TEST_MODEL_BETAAPP_1
  INNER JOIN ALL_TYPE_TABLE_SMALLER
     ON TEST_MODEL_BETAAPP_1.C_INT != ALL_TYPE_TABLE_SMALLER.C_INT and TEST_MODEL_BETAAPP_1.C_NUM != ALL_TYPE_TABLE_SMALLER.C_NUM

),

TABLE_NUM_VARIANT AS (

  SELECT * 
  
  FROM {{ source('QA_DATABASE.qa_simple_schema', 'TABLE_NUM_VARIANT') }}

),

Reformat_1 AS (

  SELECT 
    C_NUM AS C_NUM,
    C_VARIANT AS C_VARIANT,
    concat('test', C_NUM) AS c_string
  
  FROM TABLE_NUM_VARIANT AS in0

),

Join_2 AS (

  SELECT 
    in0.C_NUM10 AS C_NUM10,
    in0.C_DEC AS C_DEC,
    in0.C_NUMERIC AS C_NUMERIC,
    in0.C_INTEGER AS C_INTEGER,
    in0.C_DOUBLE AS C_DOUBLE,
    in0.C_FLOAT AS C_FLOAT,
    in0.C_COUBLE_PRECISION AS C_COUBLE_PRECISION,
    in0.C_REAL AS C_REAL,
    in0.C_VARCHAR AS C_VARCHAR,
    in0.C_VARCHAR50 AS C_VARCHAR50,
    in0.C_CHAR AS C_CHAR,
    in0.C_CHAR10 AS C_CHAR10,
    in0.C_STRING AS C_STRING,
    in0.C_STRING20 AS C_STRING20,
    in0.C_TEXT AS C_TEXT,
    in0.C_TEXT30 AS C_TEXT30,
    in0.C_BINARY AS C_BINARY,
    in0.C_BINARY100 AS C_BINARY100,
    in0.C_VARBINARY AS C_VARBINARY,
    in0.C_BOOL AS C_BOOL,
    in0.C_TIMESTAMP AS C_TIMESTAMP,
    in0.C_DATE AS C_DATE,
    in0.C_DATETIME AS C_DATETIME,
    in0.C_TIME AS C_TIME,
    in0.C_ARRAY AS C_ARRAY,
    in0.C_OBJECT AS C_OBJECT,
    in0.C_GEOGRAPHY AS C_GEOGRAPHY,
    in0.C_INT AS C_INT,
    in0.C_NUM AS C_NUM
  
  FROM Join_1 AS in0
  INNER JOIN Reformat_1 AS in1
     ON in0.C_VARCHAR != in1.C_STRING

)

SELECT * 

FROM Join_2
